### ISSUE TITLE
Create extension function maskify

### ISSUE THREAD

**Issue by mkdika** [mkdika/jeneric-kt#12]
**Objective**
Create `maskify` __extension function__ from `String` class, which will replace `n` length chars with maskify char from right.

**Acceptance Criteria**
- Write related unit test code under: `StringFunTests` file.
- Write the implementation code under: `StringFun` file.
- Default maskify char could be: `*`, but can be change.
- Example:
  - input: `pineapple`, len: `4`, output: `pinea****`
  - input: `pineapple`, len: `10`, output: `*********`
  - input: `pineapple`, len: `0`, output: `pineapple`
  - input: `pineapple`, len: `2`, char: `@`, output: `pineapp@@`

**NOTE:**
- You may add additional file/class/enum, if needed.
- Feel free to discuss if need any additional information or clarify.
- If you found that there are already Kotlin standard API to do it, rather than re-invent the wheel, please let us know.

**Comment by desdulianto** [comment]
ah, just noticed the issue here, i will create new PR for this
